# Generated by Django 4.2 on 2023-04-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("YoutubeDL", "0002_account_delete_youtubemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DLurls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.URLField(max_length=400)),
            ],
        ),
    ]
