# Generated by Django 4.2 on 2023-04-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APPLIST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("APPNAME", models.CharField(max_length=100)),
                ("APPURL", models.CharField(max_length=100)),
            ],
        ),
    ]
